### ISSUE TITLE
Won't compile with kernel >= 6.6

### ISSUE THREAD

**Issue by perezmeyer** [acontis/atemsys#3]
Trying to compile against a kernel >= 6.6 brings:

```
$ LANG=C make
make -C /lib/modules/6.6.15-amd64/build M=/home/lisandro/damian/ics/repos/kinarm/atemsys modules
make[1]: Entering directory '/usr/src/linux-headers-6.6.15-amd64'
  CC [M]  /home/lisandro/damian/ics/repos/kinarm/atemsys/atemsys.o
/home/lisandro/damian/ics/repos/kinarm/atemsys/atemsys.c: In function 'PciDriverRemove':
/home/lisandro/damian/ics/repos/kinarm/atemsys/atemsys.c:4541:5: error: implicit declaration of function 'pci_disable_pcie_error_reporting' [-Werror=implicit-function-declaration]
 4541 |     pci_disable_pcie_error_reporting(pPciDev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lisandro/damian/ics/repos/kinarm/atemsys/atemsys.c: In function 'PciDriverProbe':
/home/lisandro/damian/ics/repos/kinarm/atemsys/atemsys.c:4577:5: error: implicit declaration of function 'pci_enable_pcie_error_reporting' [-Werror=implicit-function-declaration]
 4577 |     pci_enable_pcie_error_reporting(pPciDev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.6.15-common/scripts/Makefile.build:248: /home/lisandro/damian/ics/repos/kinarm/atemsys/atemsys.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.6.15-common/Makefile:1938: /home/lisandro/damian/ics/repos/kinarm/atemsys] Error 2
make[1]: *** [/usr/src/linux-headers-6.6.15-common/Makefile:246: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.6.15-amd64'
make: *** [Makefile:28: modules] Error 2
```

Seems that API is no longer available on those kernels.

**Comment by perezmeyer** [comment]
I did try to build it using current Debian unstable, but then I looked for that function on the kernel and indeed it is no longer available in 6.6 onwards.

**Comment by ec-support** [comment]
fixed with Release v1.4.30
